apiVersion: v1
kind: Secret
metadata:
  name: jenkins-jcasc-secrets
  namespace: jenkins
type: Opaque
stringData:
  JENKINS_ADMIN_USER: admin
  JENKINS_ADMIN_PASSWORD: "admin"
  GITHUB_TOKEN: "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"
  DOCKER_USERNAME: "bourgeoisie"
  DOCKER_PASSWORD: "Hocon-181"
