#apps/jenkins/templates/jenkins-casc-configmap.yaml:
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-external
  namespace: {{ .Release.Namespace }}
data:
  "01-security.yaml": |
{{ .Files.Get "jcasc/01-security.yaml" | indent 4 }}
  "02-kubernetes-cloud.yaml": |
{{ .Files.Get "jcasc/02-kubernetes-cloud.yaml" | indent 4 }}
  "03-credentials.yaml": |
{{ .Files.Get "jcasc/03-credentials.yaml" | indent 4 }}
