apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-casc-external
  namespace: {{ .Release.Namespace }}
data:
{{- $files := .Files.Glob "jcasc/*.yaml" }}
{{- range $path, $content := $files }}
  {{ base $path }}: {{ $content.AsConfig | quote }}  # ✅ AsConfig → string
{{- end }}
