loki:
  commonConfig:
    replication_factor: 1  # Single AZ / single binary

  # Cấu hình storage cấp high-level cho chart
  storage:
    type: s3
    bucketNames:
      chunks: iot-bme680-loki-chunks
      ruler: iot-bme680-loki-ruler
      admin: iot-bme680-loki-admin
    s3:
      region: ap-southeast-1
      s3ForcePathStyle: false

  schemaConfig:
    configs:
      - from: "2026-01-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  limits_config:
    retention_period: 168h  # 7 ngày

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  persistence:
    enabled: true
    size: 10Gi
    storageClass: gp3

  serviceAccount:
    create: true
    name: loki-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::408279620390:role/loki-s3-role

monitoring:
  selfMonitoring:
    enabled: false
  serviceMonitor:
    enabled: false

gateway:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
