loki:
  commonConfig:
    replication_factor: 1  # Single AZ / single binary

  # Cấu hình storage cấp high-level cho chart
  storage:
    type: s3
    bucketNames:
      chunks: loki-chunks
      ruler: loki-ruler
      admin: loki-admin
    s3:
      region: ap-southeast-1
      bucketnames: iot-bme680-data-lake-prod
      s3ForcePathStyle: false

  # Cấu hình storage thực tế cho Loki (phần Loki đọc)
  storage_config:
    aws:
      s3: s3://ap-southeast-1/iot-bme680-data-lake-prod
      bucketnames:
        chunks: iot-bme680-data-lake-prod
        ruler: iot-bme680-data-lake-prod
        admin: iot-bme680-data-lake-prod
      s3forcepathstyle: false
      prefix: loki/  # Tất cả dữ liệu Loki nằm dưới prefix này trong bucket
    boltdb_shipper:
      shared_store: s3
      active_index_directory: /var/loki/index
      cache_location: /var/loki/index_cache
      cache_ttl: 24h

  schemaConfig:
    configs:
      - from: "2026-01-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  limits_config:
    retention_period: 168h  # 7 ngày

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

  persistence:
    enabled: true
    size: 10Gi
    storageClass: gp3

  serviceAccount:
    create: true
    name: loki-sa
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::408279620390:role/LokiS3AccessRole

monitoring:
  selfMonitoring:
    enabled: false
  serviceMonitor:
    enabled: false

gateway:
  enabled: false

backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0
