helm:
  parameters:
  - name: images.airflow.repository
    value: 408279620390.dkr.ecr.ap-southeast-1.amazonaws.com/iot-mlops-repo
    forcestring: true
  - name: images.airflow.tag
    value: latest
    forcestring: true
