helm:
  parameters:
  - name: airflow.image.repository
    value: 408279620390.dkr.ecr.ap-southeast-1.amazonaws.com/iot-mlops-repo
    forcestring: true
  - name: airflow.image.tag
    value: commit-28d6880
    forcestring: true
