# iot-mlops-manifests/argocd-apps/airflow-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
    finalizers:
    - resources-finalizer.argocd.argoproj.io  # Prevent delete issues
spec:
  project: default
  source:
    repoURL: 'https://github.com/TranNguyenPhucAnh/iot-mlops-manifests.git'
    targetRevision: main
    path: apps/airflow
    helm:
      valueFiles:
        - values.yml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: airflow # Sẽ tự động tạo namespace này
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true  # ✅ Fix: snake_case thay vì camelCase
      - PrunePropagationPolicy=foreground # Safe delete
      - Prune=true
      - Replace=true # Force replace conflicting resources
      - ServerSideApply=true    # ✅ Handle existing resources
      - ApplyOutOfSyncOnly=true # ✅ Chỉ sync diff
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
