apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-credentials
  namespace: monitoring
type: Opaque
stringData:
  GRAFANA_LOKI_INSTANCE_ID: "1436459"
  GRAFANA_PROM_INSTANCE_ID: "2881565"
  GRAFANA_OTLP_INSTANCE_ID: "1478666"
  GRAFANA_CLOUD_API_KEY: "glc_eyJvIjoiMTYyNjIwMSIsIm4iOiJzdGFjay0xNDc4NjY2LWludGVncmF0aW9uLWdyYWZhbmEtdG9rZW4iLCJrIjoiMzZEM2JjckhrVzFPcnF5MlA0MjJGNng1IiwibSI6eyJyIjoicHJvZC1hcC1zb3V0aGVhc3QtMSJ9fQ"
