apiVersion: v1
kind: Secret
metadata:
  name: grafana-cloud-credentials
  namespace: monitoring
type: Opaque
stringData:
  GRAFANA_LOKI_INSTANCE_ID: "1436459"
  GRAFANA_PROM_INSTANCE_ID: "2881565"
  GRAFANA_OTLP_INSTANCE_ID: "1478666"
  GRAFANA_CLOUD_API_KEY: "***REMOVED***"
