jenkins:
  controller:
  
    containerEnv:
      - name: CASC_JENKINS_CONFIG
        value: "/var/jenkins_home/casc_configs,/var/jenkins_home/custom_casc_configs"
   
    componentName: jenkins-controller

    image:
      repository: jenkins/jenkins
      tag: "lts"
  
    serviceAccount:
      create: false
      name: jenkins-sa
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::408279620390:role/jenkins-controller-irsa"
  
    admin:
      existingSecret: jenkins-jcasc-secrets
      userKey: JENKINS_ADMIN_USER
      passwordKey: JENKINS_ADMIN_PASSWORD
  
    javaOpts: >
      -Xms512m
      -Xmx1024m
      -Djenkins.install.runSetupWizard=false
  
    installPlugins:
      - kubernetes
      - workflow-aggregator
      - git
      - amazon-ecr
      - pipeline-model-definition
      - docker-workflow
      - configuration-as-code
      - role-strategy
  
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1000m"
        memory: "2Gi"
  
    serviceType: ClusterIP
    servicePort: 8080
  
  agent:
    enabled: true
    image:
      repository: jenkins/inbound-agent
      tag: "latest"
  
  rbac:
    create: true
    readSecrets: true
  
  persistence:
    volumes:
      - name: jenkins-custom-casc-config
        configMap:
        name: jenkins-custom-casc-config
    mounts:
      - mountPath: /var/jenkins_home/custom_casc_configs
        name: jenkins-custom-casc-config
