apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-stack
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/TranNguyenPhucAnh/iot-mlops-manifests.git
    targetRevision: main
    path: apps/kps
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
       # CRDs KPS (Prometheus, ServiceMonitor, Alertmanager) rất lớn, K8S lưu cấu hình object vào annotation, vốn limit 256KB, server (EKS Control Plane) tự quản lý việc so khớp (merge) các trường dữ liệu, loại bỏ limit
      - ServerSideApply=true
