mlflow:
  # Sửa từ Array sang Object để khớp với Schema
  extraEnv:
    # Cho phép Gunicorn chấp nhận các header Forwarded từ K8s Service/Ingress
    GUNICORN_CMD_ARGS: "--forwarded-allow-ips='*' --proxy-allow-from='*'"
    # Nếu bạn dùng một custom framework bọc ngoài có hỗ trợ biến này:
    MLFLOW_SERVER_ALLOWED_HOSTS: "*"

  backendStore:
    postgres:
      enabled: true
      host: db.airflow.local.iot-mlops-dns
      port: 5432
      database: mlflow
      user: mlflow_user
      password: mlflow_password
  
  serviceAccount:
    create: true
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::408279620390:role/AirflowAccessRole
  
  artifactRoot:
    s3:
      enabled: true
      bucket: iot-bme680-data-lake-prod
      path: mlflow-artifacts
