apiVersion: v1
kind: Secret
metadata:
  name: airflow-broker-url
  namespace: airflow
type: Opaque
stringData:
  broker-url: "cmVkaXM6Ly9haXJmbG93LXJlZGlzLm00amhsaC4wMDAxLmFwc2UxLmNhY2hlLmFtYXpvbmF3cy5jb206NjM3OS8w"
