apiVersion: v1
kind: Secret
metadata:
  name: github-dags-secret
  namespace: airflow
type: Opaque
stringData:
  GIT_SYNC_USERNAME: TranNguyenPhucAnh
  GIT_SYNC_PASSWORD: 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
  GITSYNC_USERNAME: TranNguyenPhucAnh
  GITSYNC_PASSWORD: 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
