apiVersion: v1
kind: Secret
metadata:
  name: github-dags-secret
  namespace: airflow
type: Opaque
stringData:
  GIT_SYNC_USERNAME: TranNguyenPhucAnh
  GIT_SYNC_PASSWORD: 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
  GITSYNC_USERNAME: TranNguyenPhucAnh
  GITSYNC_PASSWORD: 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
