apiVersion: v2
name: alloy-gitops
description: Grafana Alloy unified agent for Pi3 + Airflow
type: application
version: 0.1.0
dependencies:
  - name: grafana-agent
    version: "0.68.*"
    repository: https://grafana.github.io/helm-charts
