apiVersion: v2
name: alloy-gitops
description: Grafana Alloy unified agent for Airflow
type: application
version: 0.1.0
dependencies:
  - name: alloy
    version: "1.6.0"
    repository: https://grafana.github.io/helm-charts
  - name: kube-state-metrics
    version: "7.2.0"
    repository: https://prometheus-community.github.io/helm-charts
