replicaCount: 1

image:
  repository: cloudflare/cloudflared
  pullPolicy: IfNotPresent
  tag: "latest"

# Thông tin Tunnel lấy từ Cloudflare Zero Trust Dashboard
tunnel:
  token: "eyJhIjoiOTM1YmM3Y2VkYmY4NzBlYmYwMmQ4Njg3ZGE5Mjc5OTciLCJ0IjoiNTZiZGZkZjItYmU4MS00NzAzLWJmMDgtZjE4MDY4NTg0Y2ViIiwicyI6IlptVXpabVEzWlRZdE56WXdaQzAwTkRVMExUZzJPRGd0T0RCa1pEUXhPV015WkdObCJ9"
  secretName: cloudflared-eks-token

# Cấu hình đích đến bên trong cụm EKS
service:
  name: loki
  namespace: monitoring
  port: 3100

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi
